### ISSUE TITLE
Diffusion reactor not correct work and blow. 

### ISSUE THREAD

**Issue by WindofRus** [Catana791/Asthosus#100]
Game version - 146.
Mod version - Asthosus-1.5.2.

![0](https://github.com/user-attachments/assets/c6cda5cf-88c4-4688-b332-f602129f7852)

![2](https://github.com/user-attachments/assets/8e264a10-7ddd-472a-bbf5-4f2b9183f61f)

The description of the diffusion reactor says that without nontragen it explodes, but when there is a heat supply, it also explodes with it, this needs to be fixed.

**Comment by BSp-2** [comment]
Well this is fucking funny

It explodes when there IS HEAT and NO NOTRAGEN. not when there is nothing

**Comment by WindofRus** [comment]
Then need change it or writed in description that need two gas nontragen and tetraftorid silicone to not blow.

**Comment by BSp-2** [comment]
> Then need change it or writed in description that need two gas nontragen and tetraftorid silicone to not blow.

Read the description correctly. It does now explode when there is heat and notragen, but doesnt work. It does explode when there is only heat. Id works properly when there is notragen, silicon tetrafluoride and heat. It exllodes when there is heat and silicon tetrafluoride but no notragen. It doesnt work when there is notragen and silicon tetrafluoride but no heat. Whats the point of this thread anyways? You knowing english bad - leading to misunderstanding the description

**Comment by BSp-2** [comment]
And probably also new's problem since of bad translation :-:

**Comment by WindofRus** [comment]
![3(1)](https://github.com/user-attachments/assets/807ba4e7-fdd0-4f70-8fba-a96a25422760)

In description it is one coolant not a coolant.

**Comment by WindofRus** [comment]
Nontragen is coolant, right?

**Comment by timofeja19** [comment]
Translation fixed
