### ISSUE TITLE
Minor Suggestions

### ISSUE THREAD

**Issue by secretmeister** [Catana791/asthosus#34]
I am currently playing through the mode's campaign, and have a few minor suggestions.

- Either buff the basic wall drills, or offer a boosting option. In the current state it takes forever to acquire thousands of demetite and ferrinite.
- Add some early game uses for heat/pressure. You can get both of these quite early, but there is almost no use for them at the point at which you unlock them. 
- Maybe add power requirements for some of the resource factories? It feels weird for none of them to need anything other than the direct item inputs. It might feel more put together if they needed power or heat or something.

Other than those minor points, this mod has been a ton of fun so far! Am about to go to Immist and figure out unit production!

**Comment by secretmeister** [comment]
(also I love making ideas, so if you ever need ideas for anything in progression I would be happy to help)

**Comment by overdramaticpanromantic** [comment]
WallCrafters (the basic wall drills' type) can't have boosters, as the code doesn't allow for it. You can usually just build more, and it incentivizes expansion. Later on, you unlock better ones to make more use of the space you have. I can't really answer the other two suggestions, though, because I'm kind of just a helper who makes maps and such.

**Comment by Catana791** [comment]
Asthosus is heavily logistics based. Thus, I will not be buffing the normal wall crafters.
You are supposed to plan your logistics in a way that works with the resources present on each map.

Heat and pressure are introduced early to give a chance to research all of it but pressure becomes more important early/midgame while heat is mainly prominent in lategame.

For the third point, which resource factories are you talking about in particular?

**Comment by secretmeister** [comment]
Lodestone, Lithium, and Creotite require nothing other than the basic resource inputs, which just feels strange to me.

**Comment by overdramaticpanromantic** [comment]
If I recall correctly, Cretite used to require pressure, but it was deemed to have too many inputs for what Cretite is worth.

**Comment by Catana791** [comment]
Lodestone and Lithium crafters (at least the first tier) don't require power to make it easier to create them early game. I am not sure if you mean that.

Cretite is exactly as @overdramaticpanromantic said.
