### ISSUE TITLE
Materials problem

### ISSUE THREAD

**Issue by fulltimeasssniffer** [Catana791/asthosus#36]
The mod is great, but I advise you to slightly increase the efficiency of mining machines. 0.5 per second is not enough, considering that there are not many places for mining. This is the second wish: make the location have more places for mining, and places where a unit can mine itself straight into the core, if something suddenly goes wrong and the main building material runs out. Personally i think that the energy transfer idea is something unusual, but maybe making wires a bit thinner would be great. 

Good luck with developing! I hope you will introduce more interesting ideas and mechanics soon.

**Comment by Catana791** [comment]
No to all of those. Resources are limited for a reason. It forces you to plan how you'll use them and create your production accordingly.
