### ISSUE TITLE
Wrong texture folder

### ISSUE THREAD

**Issue by GalaxiumNation** [Catana791/asthosus#40]
![image](https://github.com/Catana791/asthosus/assets/84195151/d9dfe11d-7248-44ba-a34d-b20f3c1d3cf9)
![image](https://github.com/Catana791/asthosus/assets/84195151/5f55c4a6-9de9-43ad-b2fb-308c8893587a)
Idk what texture it is supposed to display but just wanted to tell ya

**Comment by Catana791** [comment]
I have seen this a few times now. It works normally for almost all players. 
Can you give me some more information?
Like
1. What platform do you use (android, Windows, ios?)
2. Do you use foos client?
3. What game version are you using?

**Comment by camelStyleUser** [comment]
could you run `Vars.world.tile(x,y)` with the x and y of the tile and give the output too

**Comment by Catana791** [comment]
Since I am getting no answer on this, I'll consider it completed.
