### ISSUE TITLE
Problems with sectors/planets translation

### ISSUE THREAD

**Issue by malomaster** [Catana791/asthosus#47]
Hi.
While playing Asthosus mod, I noticed that some items, blocks, and units weren't translated into Russian. Furthermore, I discovered that the existing translation was inadequate. Therefore, I modified the translation and translated the non-translated items. For now, I have new translations stored in my external translation mod.
However, upon attempting to translate the names and descriptions of planets and sectors, I discovered that the translated strings do not appear in the game, despite my efforts to use translation files from two other mods that add new sectors and planets as an example.
When I compared your sectors hjsons and hjsons from those two mods, I found that those mod files DOESN'T CONTAIN strings "**localizedName**" (or just "**name**") and "**description**" because all names/descriptions stored in "_bundles/bundle.properties_", so they can be easily localized without any problems.
Because of this I STRONGLY suggest you to move all name/description strings from planets and sectors hjson files to bundle.properties, because now it's impossible to localize them.

**Comment by Kenny-Ofc** [comment]
i think you may found out, the tutorial texts from the map objectives aren't move yet, catser know about it, well probably soon. Russian Translation work properly i guess.

**Comment by malomaster** [comment]
I just now tried to move planet names/desc. and first five sectors names/desc. drom hjsons to bundle.properties — and RU translation for those sectors (and even planets) worked as it should. And I spent less than 15 minutes on this. All this can be done in one hour or even faster. If @Catana791 wanted, I can finish tomorrow the rest of this work and upload a zip with "bundle.properties" with all those strings and edited hjsons, since I'm doing it anyway.

**Comment by Kenny-Ofc** [comment]
> I just now tried to move planet names/desc. and first five sectors names/desc. from hjsons to bundle.properties — and RU translation for those sectors (and even planets) worked as it should. And I spent less than 15 minutes on this. All this can be done in one hour or even faster. If @Catana791 wanted, I can finish tomorrow the rest of this work and upload a zip with "bundle.properties" with all those strings and edited hjsons, since I'm doing it anyway.

well, have you join the community?? go ahead neet other RU Translator

**Comment by malomaster** [comment]
> I can finish tomorrow the rest of this work and upload a zip with "bundle.properties" with all those strings and edited hjsons

Already completed this. [Here](https://drive.google.com/file/d/1XuDbjAnJOti4LsSMAPyPryS_Dda7F8LN/view?usp=sharing) (Google drive).
About RU translation — I'll finish it tomorrow and just upload here.

**Comment by Kenny-Ofc** [comment]
alright gotcha

**Comment by Catana791** [comment]
There is no need to move the rest of the English Strings to bundle.properties.

**Comment by malomaster** [comment]
If you wanted, here is an updated RU translation.
Если кто-то хочет, вот обновлённый перевод, исправленный (во-первых, доставлена огромная куча пропущенных запятых, во-вторых, текст приведён в соответствие с нормами русского языка — в частности, в русском языке грамотные люди Не Пишут Каждое Слово С Большой Буквы В Названии Чего-либо) и дополненный отсутствующим переводом (названия/описания карт и планет, 1 не переведённый юнит, несколько построек, 2 статус-эффекта).
[Google drive](https://drive.google.com/file/d/1FpHsOgvPvNC-bpwRtvnSB31C4Vw2x3BK/view?usp=sharing)

Возможно, позже, когда я всё-таки возьмусь пройти кампанию Афосус полностью, перевод будет отредактирован (большую часть правок описания юнитов и турелей, в частности, эффектов их оружия приходилось переводить, не видя, как они реально работают в игре, отчего где-то могут быть неточности).
