### ISSUE TITLE
scrambled items 

### ISSUE THREAD

**Issue by zef126** [Catana791/asthosus#65]
The items are going in build path where they have nothing to do!
![Screenshot_2024-08-20-00-25-17-971_io anuke mindustry](https://github.com/user-attachments/assets/6ef3e4a0-d701-4ba2-8a62-8b01ef7730ab)
This is on serpulo!

**Comment by Kenny-Ofc** [comment]
what do you mean? that is an ore patch, you can mine it

**Comment by Kenny-Ofc** [comment]
bruh, if those modded content disturbing you, disabled it! They are usable in Planet Asthosus, change your planet by click on the planet map

**Comment by Kenny-Ofc** [comment]
> It is serpulo, there is nowhere to mine ferrinite, but the mine is there! Items of a mod that contain a planet must only appear on the building menu of the planet bot! The items of asthrosus are disturbing me all over the other planet because they are in this menu without being usable!

you want play Asthosus right? change the planet. why people not easily understand the game. you're on serpulo, then play serpulo, if you want to play erekir, change the planet into erekir. same as other planet mod, they'd have own planet

**Comment by BSp-2** [comment]
What is the problem here anyways? I dont see a one

**Comment by Catana791** [comment]
There is no way for me to properly disable Asthosus content on Serpulo. 

If you want to play Serpulo, just disable Asthosus in thr meantime.

@zef126

**Comment by zef126** [comment]
In all other mods, this is possible!

**Comment by BSp-2** [comment]
What mods?

**Comment by BSp-2** [comment]
Fading revelations - no
If i remember correctly, frozen farlands - no
Meld - no
Biotech - no
Zeridmuth - no
What are you talking about

**Comment by BSp-2** [comment]
![Screenshot_20240820_094731](https://github.com/user-attachments/assets/f6ebbda6-b5b3-4e07-a96a-42052f33150d)
Heres where you choose the planet if you dont know (i dont even know how you can not), AND on asthosus theres no SERPULO or EREKIR content at all

**Comment by zef126** [comment]
@BSp-2 your list is false!
I have these mods and they don't have this problem!

**Comment by Kenny-Ofc** [comment]
> ![Screenshot_20240820_094731](https://private-user-images.githubusercontent.com/171292228/359366612-f6ebbda6-b5b3-4e07-a96a-42052f33150d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzY5NzksIm5iZiI6MTcyNDEzNjY3OSwicGF0aCI6Ii8xNzEyOTIyMjgvMzU5MzY2NjEyLWY2ZWJiZGE2LWI1YjMtNGUwNy1hOTZhLTQyMDUyZjMzMTUwZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNjUxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTI2MWZhNWU5NTFlNjMxZTE0M2I0NDE0NjZjYWQyOTZlMmU1MTkwOTFmZGNjNWZlZjZmZWIxZDkyOWFhOTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2Kea6sATxngMIEqvVx5f8idM60Z96F98a8N5vZZ-lvY) Heres where you choose the planet if you dont know (i dont even know how you can not), AND on asthosus theres no SERPULO or EREKIR content at all

it was! sigh... man, on Asthosus you can't use Serpulo/Erekir tech. that was so clear. buddy what do you want huh, 

you're dumb ass,  Make it clear, Vanilla content can only being used on Serpulo and Erekir each of them. You want Asthosus content? play on Asthosus. You want Erekir? play on erekir, is that not so easily to understand!

**Comment by BSp-2** [comment]
Fading revelations Too?

**Comment by zef126** [comment]
This mod is making concurrency to the game it was programmed for, it is not ethical for a mod dev!
I hope this is unpurpose! It looks like an insult to the game dev if it is!

**Comment by thetrulystupid** [comment]
please just shut up already zef

**Comment by BSp-2** [comment]
![Screenshot_20240820_095909](https://github.com/user-attachments/assets/922d715c-43aa-4262-9bb8-69df63474c2e)
![Screenshot_20240820_095900](https://github.com/user-attachments/assets/d7c62fbc-6c20-44d5-88ff-94a78851d2e6)
![Screenshot_20240820_095925](https://github.com/user-attachments/assets/751c92fa-06d9-4f09-877a-136e1f6ed1a2)
![Screenshot_20240820_100008](https://github.com/user-attachments/assets/914eab8f-b71b-4f5d-8479-7965f5c81c9f)
![Screenshot_20240820_095939](https://github.com/user-attachments/assets/32a11d59-304d-424b-9971-de815d76e78f)
![Screenshot_20240820_095956](https://github.com/user-attachments/assets/6e77a82a-f9b3-4561-b664-c00e76fd0521)
Look man. I have asthosus on. There no asthosus content on serpulo, but there is from frozen farlands, zeridmuth, aeyama and meld. What the hell are you talking about asthosus being on serpulo

**Comment by Kenny-Ofc** [comment]
the guy name zef are truly not understanding the game! freak

**Comment by BSp-2** [comment]
Not ethical for mod dev blah blah do you even know how frigin hard he works to make this mod while javing to go to work and his own life, and you complain about something that players from all the world dont even care about

**Comment by zef126** [comment]
I know you are working hard and I think your work is amazing but your reaction to a problem gently reported made me overreact, can we now examine the problem fully?
I finished the game on my ancient phone!

**Comment by Kenny-Ofc** [comment]
> I know you are working hard and I think your work is amazing but your reaction to a problem gently reported made me overreact, please excuse me! Can we now examine the problem fully? I finished the game on my ancient phone!

discuss it further on discord instead

**Comment by zef126** [comment]
Ok...how?

**Comment by Kenny-Ofc** [comment]
> Ok...how? I am not on the server!

you're already on github. look over the readme of this repository

**Comment by BSp-2** [comment]
@zef126
https://discord.gg/uFucSVznzA
