### ISSUE TITLE
.jar request

### ISSUE THREAD

**Issue by daedaevibin** [Catana791/asthosus#74]
PLEASE make a .jar of this sonic can create a server I can run on my laptop with this mod. I have family members I play mindustry with because they enjoy it (even when they struggle a lot) and I would LOVE for everyone to be able to participate in it at all times of day whenever they liked.

I would also enjoy if you created music for the planet you created, and some replacement music for Erekir and Serpulo.

Keep up the good work though

**Comment by Catana791** [comment]
I am not sure that I can make a jar of this mod.

There is actually music for Asthosus but it's in a separate mod called Asthosus OST.

**Comment by Catana791** [comment]
The three white dots are just part of the new icon. The Ost mod works normally on the current release version but you may sometimes hear regular mindustry music because not all of the tracks have been replaced with Asthosus music yet.

**Comment by daedaevibin** [comment]
> The three white dots are just part of the new icon. The Ost mod works normally on the current release version but you may sometimes hear regular mindustry music because not all of the tracks have been replaced with Asthosus music yet.

No, it just stopped working. There's no replacements of any music on anything for an unknown reason


I would like to make a request though, possibly some planet music for the planet in the future? Maybe some music to replace Erekir and Serpulos music?

**Comment by daedaevibin** [comment]
> I really can't tell what is actually going on here.
> 
> Asthosus OST basically works for everyone who has ever used it. 
> 
> It has had no changes that should affect its functionality at all. 
> Can you provide some "proof" of your situation?

Screen recordings don't capture audio, and I've brought this up in the server as well. I asked about if it were possible to send log files or not too. All to no avail though

**Comment by Catana791** [comment]
This post hasn't been updated for an extensive amount of time and is thus considered stale.

Stale posts will be closed.
