### ISSUE TITLE
Felesa file

### ISSUE THREAD

**Issue by BSp-2** [Catana791/asthosus#76]
Since im using discord.com rn i cant send the file in there. 
[Felesafix.zip](https://github.com/user-attachments/files/16974259/Felesafix.zip)
Just rename the file into .msav after downloading.

Fixes:
- removed that stupid core
- banned several blocks
- shortened the amount of sandstorms
- fixed some world logic

Alright i hope this is the final ver and me dumb shit wont update it more

If the map is unfun, its gonna be a custom map then. :(
No required researches then

**Comment by Catana791** [comment]
Since you have Discord access again, I will be closing this without making anything of it.
