### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Kilomatric** [Catana791/Asthosus#80]
Idk why but when I change mod, all of my asthosus sector will turn most of the belt with resources on it into copper from serpulo. My second issue is that any sector will corrupt if there is or I built a Petra core or higher than that type of core. I want asthosus but I can't literally play it because of this :(

**Comment by Kenny-Ofc** [comment]
are you having another mod enabled? it is known issue, if there's more than 1 planet mod enabled. it would sometimes corrupt ur saves.

**Comment by Kenny-Ofc** [comment]
are you having another mod enabled? it is known issue, if there's more than 1 planet mod enabled. it would sometimes corrupt ur saves.

**Comment by Catana791** [comment]
@Kilomatric as Kenny already asked above, do you have another campaign/planet mod enabled?
Having multiple of these mods enabled is known to cause conflicts and issues.

If this is not the case, have you recently updated the mod? 
A few map files were changed recently to upgrade them which could corrupt their save files.

If you have any more questions or want to give me more info on this, feel free to ping me here or join the Asthosus Discord server.

**Comment by Kilomatric** [comment]
Oh, so it was the another mods fault... Then maybe my last issue is the worm type core units because I tried it with or without an another mod but it still just says "Save error or corrupted."

**Comment by Catana791** [comment]
@Kilomatric does that "save error or corrupted" message also appear when you abandon the sector and launch there again?

Please provide me with the sector name.

**Comment by Kilomatric** [comment]
Every sector with an Petra core or higher than that type, but it doesn't appear when I abandon the sector. I have no issues like that. As long as I avoid that type of core, I can play easily.

**Comment by Kilomatric** [comment]
Btw, It also corrupts when I build one.

**Comment by Catana791** [comment]
I have never heard of this exact issue before. 
Furthermore, I have been unable to replicate it. 

@Kilomatric if it doesn't get any better than this, you might actually need to reset your save file...

Closing the issue because of the reasons mentioned above.
