### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Catana791** [Catana791/Asthosus#85]

**Comment by BSp-2** [comment]
Nice issue 👍👍👍

**Comment by Kenny-Ofc** [comment]
He testing Stale Workflow u silly :angy:

**Comment by Catana791** [comment]
If you are visiting this issue: This is a test issue that I am using to test the automatic marking of issues as stale and the automatic closing of stale issues after a specific amount of time. 

Please do NOT send any messages or add any comments here. Please DO leave this issue exactly as it is right now as any activity will reset the stale state timer.
