### ISSUE TITLE
problem involving player access to T3+ units...

### ISSUE THREAD

**Issue by yesC48** [Catana791/Asthosus#94]
**Describe the bug**
Due to technical constraints, module tier 2+ unit build plans can't be. Refer to the video below.

**To Reproduce**
1. Build ANY Assembly Bay
2. Use anything above an Elementary Assembly Constituent

**Expected behavior**
You can't build up to a Cleaver/Aprotodon/Illuminate/Decredence.

**Screenshots**

https://github.com/user-attachments/assets/1777af7c-c2d8-463b-896a-d6f9540d6957

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone 4 Pro

**Comment by Kev-Vily** [comment]
skull for you. Bro aren't even read the description of the block ? to build t2 you need basic Assembler constituents, and add upgraded constituents, not remove the previous one. 

simple to understand = build T3 need = Basic Assembler Constituents AND & AND Advanced Assembler Constituents

then go on add another upgraded constituents to make T4. Bro ?

**Comment by yesC48** [comment]
> skull for you. Bro aren't even read the description of the block ? to build t2 you need basic Assembler constituents, and add upgraded constituents, not remove the previous one.
> 
> simple to understand = build T3 need = Basic Assembler Constituents AND & AND Advanced Assembler Constituents
> 
> then go on add another upgraded constituents to make T4. Bro ?

i mean thanks for pointing it out like that but... eh, don't be condescending like that...
