### ISSUE TITLE
Нет поставки жидкости для ускорения пушки Уточнитель. 

### ISSUE THREAD

**Issue by WindofRus** [Catana791/Asthosus#95]
Нет поставки жидкости для ускорения пушки Уточнитель.

Версия игры 146.
Версия мода - Asthosus-1.5.2. 

![Screenshot_20241226_181728](https://github.com/user-attachments/assets/56c6b437-123a-4af8-88b1-10ebcc9f68d5)

![1](https://github.com/user-attachments/assets/71e248ff-1f76-49b1-bbed-454dbfb820f3)

![Screenshot_20241226_181756](https://github.com/user-attachments/assets/c4c59565-d8ce-4872-bac6-0f7f1a541bb9)

Требую исправить.

**Comment by BSp-2** [comment]
Это визуальный баг, можно и не обращять внимания

**Comment by Catana791** [comment]
Please submit issues in English. I will not take a look at them otherwise.

**Comment by WindofRus** [comment]
Why?
