### ISSUE TITLE
В Аккумуляторе весмония нет 900% эффективности. 

### ISSUE THREAD

**Issue by WindofRus** [Catana791/Asthosus#96]
Версия игры - 146.
Версия мода - Asthosus-1.5.2.

В Аккумуляторе весмония нет 900% эффективности.

![1](https://github.com/user-attachments/assets/b013b951-42c5-401d-aca3-07bb9cb27591)

Требую исправить.

**Comment by BSp-2** [comment]
Это не баг, так задумано чтобы если поставить даже на 1 клетку барита аккумулятор он работал на 225%.

Плюс, подумай сам, 900% это както слишком имбово

**Comment by Catana791** [comment]
Please submit issues in English. I will not take a look at them otherwise.

**Comment by WindofRus** [comment]
> Это не баг, так задумано чтобы если поставить даже на 1 клетку барита аккумулятор он работал на 225%.
> 
> Плюс, подумай сам, 900% это както слишком имбово

Так конвейер последний по 50 единиц в секунду пропускает.
