### ISSUE TITLE
No supply of gun acceleration fluid Clarifier.

### ISSUE THREAD

**Issue by WindofRus** [Catana791/Asthosus#98]
No supply of gun acceleration fluid Clarifier.

Game version 146.
Mod version - Asthosus-1.5.2.

![Screenshot_20241226_181728](https://github.com/user-attachments/assets/56c6b437-123a-4af8-88b1-10ebcc9f68d5)

![1](https://github.com/user-attachments/assets/71e248ff-1f76-49b1-bbed-454dbfb820f3)

![Screenshot_20241226_181756](https://github.com/user-attachments/assets/c4c59565-d8ce-4872-bac6-0f7f1a541bb9)

I need it fixed.

**Comment by Catana791** [comment]
The issue here is that I am not able to just add a second liquid bar due to hjson restrictions.

The coolant does, however, still work so there would be no functional difference.

**Comment by WindofRus** [comment]
When add second bar?

**Comment by BSp-2** [comment]
> When add second bar?

Переведу на русский для особо одаренного:

Он не МОЖЕТ это сделать на хджсоне (КОД НА КОТОРОМ НАПИСАН МОД) и если даже попытается, то это может занять несколько месяцов. ПЛЮС, у него недавно было выгорание, так как он перестарался над ДЛС для мода ввиде спутника планеты, так что и этого он не будет делать. А ТАКЖЕ, охлаждение на уточнитель РАБОТАЕТ, хоть и не показывает этого когда наводиш на него мышку. Выводы: ты пришёл, к человеку, который и так в депресси изза того что недостаточно хорошо может выйти мод, плюс, ФИЗИЧЕСКИ почти не может это исправить, ПЛЮС, это ОЧЕНЬ мелкий баг, на который можно внимание и не обращять, ПЛЮС, все и так работает, так что жто еще и просто визуальный баг, ПЛЮС, ты еще и ТРЕБУЕШ исправить это. Вопрос: ты вообще знаеш хджсон или просто непонимеш сути всего этого промшедствия?

**Comment by Kev-Vily** [comment]
> When add second bar?

bro. take a read. Catser CAN'T, added another second bar of liquid DUE TO hjson restrictions. enough yapping in GitHub man, Asthosus Mod is Pretty Well Functional. why would you demanding a fix to a thing that still perfectly functional
